sonar.projectKey=OHTU_task_2
sonar.projectName=OHTU Task 2
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.coverage.exclusions=**/Main.java,**/LocalizationService.java,**/Controller.java
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000